<?php
/**
 * Test script for Dialplan Generator
 * Run from command line: php test-dialplan-generator.php
 */

// Set environment
$_SERVER['REQUEST_METHOD'] = 'CLI';

// Load CodeIgniter bootstrap
define('ENVIRONMENT', 'production');
define('BASEPATH', __DIR__ . '/system/');

// Load database config
require_once(__DIR__ . '/application/config/database.php');

// Simple test without full CodeIgniter bootstrap
echo "=== A-Dial Dialplan Generator Test ===\n\n";

// Connect to database
$dbConfig = $db['default'];
try {
    $pdo = new PDO(
        "mysql:host={$dbConfig['hostname']};dbname={$dbConfig['database']};charset=utf8mb4",
        $dbConfig['username'],
        $dbConfig['password'],
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
    );

    echo "✓ Database connected\n\n";

    // Load IVR menus
    $stmt = $pdo->query("
        SELECT m.*,
               GROUP_CONCAT(
                   CONCAT_WS('|', a.dtmf_digit, a.action_type, a.action_value, a.channel_type)
                   ORDER BY a.dtmf_digit
                   SEPARATOR ';;'
               ) as actions_data
        FROM ivr_menus m
        LEFT JOIN ivr_actions a ON a.ivr_menu_id = m.id
        GROUP BY m.id
        ORDER BY m.id
    ");

    $menus = $stmt->fetchAll(PDO::FETCH_OBJ);

    echo "Found " . count($menus) . " IVR menus\n\n";

    // Build dialplan
    $dialplan = "; A-Dial Dialplan Configuration\n";
    $dialplan .= "; Auto-generated by Dialplan_generator\n";
    $dialplan .= "; Generated: " . date('Y-m-d H:i:s') . "\n;\n\n";

    // Outbound dialing context
    $dialplan .= "[dialer_out]\n";
    $dialplan .= "; Outbound dialing context - uses TRUNK variable to dial external numbers\n";
    $dialplan .= "; DIAL_TIMEOUT: time to wait for answer (15-180 sec, default 30)\n";
    $dialplan .= "; CALL_TIMEOUT: max call duration after answer (30-3600 sec, default 600)\n";
    $dialplan .= "exten => _X.,1,NoOp(Dialer Outbound: \${EXTEN} via \${TRUNK})\n";
    $dialplan .= " same => n,Set(CDR(accountcode)=\${CAMPAIGN_ID})\n";
    $dialplan .= " same => n,Set(CDR(userfield)=\${CAMPAIGN_ID}:\${NUMBER_ID}:\${AGENT_DEST})\n";
    $dialplan .= " same => n,Set(__CAMPAIGN_ID=\${CAMPAIGN_ID})\n";
    $dialplan .= " same => n,Set(__NUMBER_ID=\${NUMBER_ID})\n";
    $dialplan .= " same => n,Set(__DIAL_TIMEOUT=\${DIAL_TIMEOUT})\n";
    $dialplan .= " same => n,Set(__CALL_TIMEOUT=\${CALL_TIMEOUT})\n";
    $dialplan .= " same => n,Set(__DIALED_NUMBER=\${DIALED_NUMBER})\n";
    $dialplan .= " same => n,Set(__DIALED_NAME=\${DIALED_NAME})\n";
    $dialplan .= " same => n,Set(__AGENT_DEST=\${AGENT_DEST})\n";
    $dialplan .= " same => n,Set(YEAR=\${STRFTIME(\${EPOCH},,\%Y)})\n";
    $dialplan .= " same => n,Set(MONTH=\${STRFTIME(\${EPOCH},,\%m)})\n";
    $dialplan .= " same => n,Set(DAY=\${STRFTIME(\${EPOCH},,\%d)})\n";
    $dialplan .= " same => n,Set(CALLFILENAME=\${UNIQUEID}-\${EXTEN}-\${CAMPAIGN_ID})\n";
    $dialplan .= " same => n,Set(RECORDING_PATH=/var/spool/asterisk/monitor/dialer/\${YEAR}/\${MONTH}/\${DAY}/\${CALLFILENAME}.wav)\n";
    $dialplan .= " same => n,System(mkdir -p /var/spool/asterisk/monitor/dialer/\${YEAR}/\${MONTH}/\${DAY})\n";
    $dialplan .= " same => n,MixMonitor(\${RECORDING_PATH},b)\n";
    $dialplan .= " same => n,Set(CDR(recordingfile)=\${RECORDING_PATH})\n";
    $dialplan .= " same => n,Dial(\${TRUNK}/\${EXTEN},\${DIAL_TIMEOUT})\n";
    $dialplan .= " same => n,UserEvent(DialStatus_A,Campaign:\${CAMPAIGN_ID},Number:\${NUMBER_ID},Status:\${DIALSTATUS})\n";
    $dialplan .= " same => n,GotoIf(\$[\"\${DIALSTATUS}\" != \"ANSWER\"]?hangup)\n";
    $dialplan .= " same => n,Hangup()\n";
    $dialplan .= " same => n(hangup),Hangup()\n\n";

    // Agent destination context
    $dialplan .= "[dialer_agent]\n";
    $dialplan .= "; Agent destination context - dials agent extension using CHANNEL_TYPE\n";
    $dialplan .= "; Uses CALL_TIMEOUT to limit maximum conversation duration (L option in milliseconds)\n";
    $dialplan .= "; Sets CallerID to show dialed number and name from campaign\n";
    $dialplan .= "exten => _X.,1,NoOp(Dialer Agent: Connecting to \${CHANNEL_TYPE}/\${EXTEN})\n";
    $dialplan .= " same => n,Set(CDR(accountcode)=\${CAMPAIGN_ID})\n";
    $dialplan .= " same => n,Set(CALLERID(num)=\${DIALED_NUMBER})\n";
    $dialplan .= " same => n,Set(CALLERID(name)=\${DIALED_NAME})\n";
    $dialplan .= " same => n,Set(CALL_TIMEOUT_MS=\$[\${CALL_TIMEOUT}*1000])\n";
    $dialplan .= " same => n,UserEvent(AgentConnect,Campaign:\${CAMPAIGN_ID},Number:\${NUMBER_ID},Agent:\${EXTEN},ChannelType:\${CHANNEL_TYPE})\n";
    $dialplan .= " same => n,Dial(\${CHANNEL_TYPE}/\${EXTEN},\${DIAL_TIMEOUT},L(\${CALL_TIMEOUT_MS}))\n";
    $dialplan .= " same => n,UserEvent(DialStatus_B,Campaign:\${CAMPAIGN_ID},Number:\${NUMBER_ID},Status:\${DIALSTATUS},Dest:\${EXTEN})\n";
    $dialplan .= " same => n,Hangup()\n\n";

    // Queue destination context
    $dialplan .= "[dialer_queue]\n";
    $dialplan .= "; Queue destination context - puts caller into queue\n";
    $dialplan .= "; Uses CALL_TIMEOUT to limit maximum time in queue + conversation\n";
    $dialplan .= "; Sets CallerID to show dialed number and name from campaign\n";
    $dialplan .= "exten => _X.,1,NoOp(Dialer Queue: Adding to queue \${EXTEN})\n";
    $dialplan .= " same => n,Set(CDR(accountcode)=\${CAMPAIGN_ID})\n";
    $dialplan .= " same => n,Set(CALLERID(num)=\${DIALED_NUMBER})\n";
    $dialplan .= " same => n,Set(CALLERID(name)=\${DIALED_NAME})\n";
    $dialplan .= " same => n,Set(TIMEOUT(absolute)=\${CALL_TIMEOUT})\n";
    $dialplan .= " same => n,UserEvent(QueueConnect,Campaign:\${CAMPAIGN_ID},Number:\${NUMBER_ID},Queue:\${EXTEN})\n";
    $dialplan .= " same => n,Queue(\${EXTEN},t,,,\${DIAL_TIMEOUT})\n";
    $dialplan .= " same => n,UserEvent(DialStatus_B,Campaign:\${CAMPAIGN_ID},Number:\${NUMBER_ID},Status:\${QUEUESTATUS},Dest:\${EXTEN})\n";
    $dialplan .= " same => n,Hangup()\n\n";

    // IVR contexts
    foreach ($menus as $menu) {
        $dialplan .= "[ivr-menu-{$menu->id}]\n";
        $dialplan .= "; IVR: {$menu->name}\n";
        $dialplan .= "; Sets CallerID to show dialed number and name from campaign\n";
        $dialplan .= "exten => s,1,NoOp(IVR Menu: {$menu->name})\n";
        $dialplan .= " same => n,Answer()\n";
        $dialplan .= " same => n,Set(CALLERID(num)=\${DIALED_NUMBER})\n";
        $dialplan .= " same => n,Set(CALLERID(name)=\${DIALED_NAME})\n";
        $dialplan .= " same => n,Wait(1)\n";
        $dialplan .= " same => n,Set(TIMEOUT(digit)=5)\n";
        $dialplan .= " same => n,Set(TIMEOUT(response)={$menu->timeout})\n";

        $audioPath = '/var/lib/asterisk/sounds/dialer/' . pathinfo($menu->audio_file, PATHINFO_FILENAME);
        $dialplan .= " same => n,Background({$audioPath})\n";
        $dialplan .= " same => n,WaitExten({$menu->timeout})\n\n";

        // Parse and add actions
        if ($menu->actions_data) {
            $actions = explode(';;', $menu->actions_data);
            foreach ($actions as $actionStr) {
                $parts = explode('|', $actionStr);
                if (count($parts) >= 3) {
                    $digit = $parts[0];
                    $type = $parts[1];
                    $value = $parts[2];
                    $channel = $parts[3] ?? 'sip';

                    $dialplan .= "exten => {$digit},1,NoOp(Action: {$type})\n";
                    $dialplan .= " same => n,UserEvent(IVRAction,Campaign:\${CAMPAIGN_ID},Number:\${NUMBER_ID},Digit:{$digit},Action:{$type})\n";

                    switch ($type) {
                        case 'exten':
                            // Extension transfer via LOCAL channel
                            $dialplan .= " same => n,NoOp(Transferring to extension {$value} via LOCAL channel)\n";
                            $dialplan .= " same => n,Dial(LOCAL/{$value}@from-internal,60,g)\n";
                            $dialplan .= " same => n,UserEvent(DialStatus_B,Campaign:\${CAMPAIGN_ID},Number:\${NUMBER_ID},Status:\${DIALSTATUS},Dest:{$value})\n";
                            $dialplan .= " same => n,Hangup()\n";
                            break;
                        case 'queue':
                            $dialplan .= " same => n,Queue({$value},t,,,60)\n";
                            $dialplan .= " same => n,UserEvent(DialStatus_B,Campaign:\${CAMPAIGN_ID},Number:\${NUMBER_ID},Status:\${QUEUESTATUS},Dest:{$value})\n";
                            $dialplan .= " same => n,Hangup()\n";
                            break;
                        case 'goto_ivr':
                            $dialplan .= " same => n,Goto(ivr-menu-{$value},s,1)\n";
                            break;
                        case 'hangup':
                            $dialplan .= " same => n,Playback(vm-goodbye)\n";
                            $dialplan .= " same => n,Hangup()\n";
                            break;
                    }
                    $dialplan .= "\n";
                }
            }
        }

        // Timeout and invalid handlers
        $dialplan .= "exten => t,1,NoOp(Timeout)\n";
        $dialplan .= " same => n,Playback(vm-goodbye)\n";
        $dialplan .= " same => n,Hangup()\n\n";

        $dialplan .= "exten => i,1,NoOp(Invalid)\n";
        $dialplan .= " same => n,Playback(invalid)\n";
        $dialplan .= " same => n,Goto(s,4)\n\n";
    }

    // Write to file
    $file = '/etc/asterisk/extensions_dialer.conf';
    file_put_contents($file, $dialplan);

    echo "✓ Dialplan written to $file (" . strlen($dialplan) . " bytes)\n\n";

    // Reload Asterisk
    exec('asterisk -rx "dialplan reload"', $output, $returnCode);
    if ($returnCode === 0) {
        echo "✓ Asterisk dialplan reloaded\n\n";
    } else {
        echo "✗ Failed to reload dialplan\n\n";
    }

    // Show first 50 lines
    echo "=== Generated Dialplan Preview ===\n";
    $lines = explode("\n", $dialplan);
    $preview = array_slice($lines, 0, 50);
    echo implode("\n", $preview) . "\n";

    // Validate
    echo "\n=== Validation ===\n";
    exec('asterisk -rx "dialplan show dialer-origination"', $output, $returnCode);
    if ($returnCode === 0 && !empty($output)) {
        echo "✓ Dialplan is valid and loaded\n";
    } else {
        echo "✗ Dialplan validation failed\n";
    }

} catch (Exception $e) {
    echo "✗ Error: " . $e->getMessage() . "\n";
}
